version: '3'
services:
  server:
    build: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://localhost:27017/sales
    depends_on:
      - db
  client:
    build: ./client
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - WATCHPACK_POLLING=true
  db:
    image: mongo
    ports:
      - "27017:27017"
