export const DATA_FILLED = "Fake datum have been filled"
export const DATA_ADD_WRONG = "Something went wrong while adding datum"
export const DATA_SERVER_DOWN = "Server is down"
export const productCategory = [
  "Electronics",
  "Fashion",
  "Beauty and Personal Care",
  "Home and Kitchen Appliances",
  "Furniture and Home Decor",
  "Sports and Fitness Equipment",
  "Books and Stationery",
  "Toys and Games",
  "Health and Wellness",
  "Automotive and Tools",
  "Groceries and Gourmet Food",
  "Jewelry and Accessories",
  "Baby and Maternity Products",
  "Pet Supplies",
  "Office Supplies",
  "Arts and Crafts",
  "Musical Instruments",
  "Movies, Music, and Entertainment",
  "Outdoor and Camping Gear",
  "Travel and Luggage",
  "Industrial and Scientific Equipment",
  "Party Supplies",
  "Garden and Outdoor Living",
  "Watches",
  "Collectibles and Memorabilia",
];
